### PR TITLE
Update sint-server-extensions from 1.1 to 1.2

### PR DESCRIPTION
**Pull request by guusdk**
This adds new tests, but also the generation of a JUnit-XML based report

### CODE REVIEW

**Comment by Fishbowler** [comment]
I've pushed a commit that adds the permission to create the JUnit Test Report. The failure now appears to be legitimate test failure.
There's also an alternative to the extra check, to set it to `annotateOnly` (see https://github.com/mikepenz/action-junit-report/issues/23#issuecomment-1717688566) where it would only draw the table. I don't understand it well enough to know what's preferable.

**Comment by guusdk** [comment]
I failed to understand what a 'check' is, but I now do. It's one of the things that gets verified when a PR is created, like these:

image

The JUnit Report action is embedded in 'our' XMPP Interop Action. It's 'our' action that should be 'the check'. The report generation that's an integral part of it doesn't need to be, or perhaps should not be.

Another reason to not want the JUnit Report action to be a check is that it apparently requires users of _our_ Action to configure the required permission in their workflow. That's an additional configuration burden that we should avoid.

I have rewritten history in this PR to remove the permission that you added, and have replaced it with the `annotateOnly` directive that you already mentioned.

**Comment by Fishbowler** [comment]
Peering at that PubSub failure

**Comment by Fishbowler** [comment]
Hmmm. Worked on a rerun. A flake in `subscribePresenceSubscriptionRequiredTest`.
Maybe that needs an explicit `IntegrationTestRosterUtil.ensureBothAccountsAreNotInEachOthersRoster`?

**Review by Fishbowler — APPROVED** [review]

**Pull request merged**
